// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wqrtjugvhhfjezqyhhle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxcnRqdWd2aGhmamV6cXloaGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2NDUzNDksImV4cCI6MjA4MzIyMTM0OX0.OJW85DMLKCazYsdlhYyLqG9aIfgaN7cd-B36f059bA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);